import type { LegalContent } from "./types";

export const en: LegalContent = {
  index: {
    meta: {
      title: "Legal — Aktays",
      description:
        "Privacy policy, terms of service, cookie policy and accessibility statement for aktays.com.",
    },
    eyebrow: "Legal",
    title: "The small print, in plain language.",
    lead:
      "We have tried to write these the way we write everything else — clearly, and without hiding anything important in the middle of a long paragraph.",
  },
  updatedLabel: "Last updated",
  contentsLabel: "Contents",
  companyLabels: {
    legalName: "Legal name",
    address: "Registered address",
    registration: "Trade registry no.",
    taxOffice: "Tax office",
    taxNumber: "Tax number",
    email: "Email",
  },

  docs: [
    {
      slug: "privacy",
      title: "Privacy Policy",
      summary:
        "What we collect, why, who we share it with, and the rights you have over it — under both Turkish law (KVKK) and the GDPR.",
      sections: [
        {
          heading: "Who we are",
          body: [
            "Aktays is an independent design studio based in Istanbul, Türkiye. For the purposes of the Turkish Personal Data Protection Law No. 6698 (KVKK) we are the data controller (veri sorumlusu), and for the purposes of the EU General Data Protection Regulation (GDPR) we are the controller of the personal data described below.",
          ],
          showCompanyDetails: true,
        },
        {
          heading: "What this policy covers",
          body: [
            "This policy covers personal data we process through this website. It does not cover data we process under a signed client contract — that is governed by the data processing terms in the contract itself.",
          ],
        },
        {
          heading: "What we collect",
          body: [
            "Information you give us. If you submit the enquiry form, we receive your name, email address, company name, the project type, budget range and timeline you select, and whatever you write in the message field. Nothing on the form is collected covertly — what you can see is what we receive.",
            "Information collected automatically. Our hosting provider records standard server logs for every request: IP address, timestamp, requested URL, referring page and user-agent string. These are generated by the infrastructure for security and reliability purposes, not by tracking code we have added.",
            "Cookies. This site sets one cookie, and only when you actively choose a language. Full detail is in our Cookie Policy.",
          ],
        },
        {
          heading: "What we do not collect",
          body: [
            "We want to be specific about this, because most privacy policies are not. This website runs no analytics, no advertising pixels, no session recording, no heatmaps, no A/B testing tools and no third-party tracking scripts of any kind. We do not build a profile of you, and we do not sell or share data with advertisers, because we do not have any to sell.",
          ],
        },
        {
          heading: "Why we use it, and our legal basis",
          bullets: [
            "To reply to your enquiry and to have the conversation that follows. Legal basis: performance of, or steps prior to entering into, a contract (GDPR Art. 6(1)(b)); KVKK Art. 5(2)(c).",
            "To keep the site secure, available and free of abuse. Legal basis: our legitimate interest in operating a functioning website (GDPR Art. 6(1)(f)); KVKK Art. 5(2)(f).",
            "To remember your language choice. Legal basis: our legitimate interest in the site working as you expect (GDPR Art. 6(1)(f)). This cookie is strictly functional and is set only when you pick a language.",
            "To meet accounting and tax obligations, if you become a client. Legal basis: compliance with a legal obligation (GDPR Art. 6(1)(c)); KVKK Art. 5(2)(a).",
          ],
        },
        {
          heading: "Who we share it with",
          body: [
            "We use a small number of service providers, each acting as a processor on our instructions. We do not share your personal data with anyone else.",
          ],
          bullets: [
            "Vercel Inc. — website hosting and server logs.",
            "Resend (Plus Five Five, Inc.) — delivery of enquiry emails sent through the form.",
            "Google LLC — this site loads its typefaces from Google Fonts. As a result, your browser makes a request to Google's servers when you load a page, which discloses your IP address and user-agent to Google. No cookie is set by this request. If you would prefer to avoid it, a content blocker will prevent the request; the site remains fully usable with fallback typefaces.",
            "Our email provider — because your enquiry arrives in, and remains in, our inbox.",
          ],
        },
        {
          heading: "International transfers",
          body: [
            "Our providers listed above operate infrastructure outside Türkiye and, in some cases, outside the European Economic Area. Where personal data is transferred out of the EEA, those transfers are covered by the European Commission's Standard Contractual Clauses or an equivalent safeguard offered by the provider. For transfers abroad under KVKK, we rely on your explicit consent where required, or on the conditions permitted by Art. 9 of the KVKK.",
          ],
        },
        {
          heading: "How long we keep it",
          bullets: [
            "Enquiries that do not become projects: up to 24 months, so we have context if you come back to us, then deleted.",
            "Enquiries that become projects: for the duration of the engagement and for as long afterwards as Turkish tax and commercial law requires us to retain the records — generally 10 years.",
            "Server logs: retained by our hosting provider on a short rolling window, typically no more than 30 days.",
            "The language cookie: 12 months, or until you clear it.",
          ],
        },
        {
          heading: "Your rights",
          body: [
            "Under the GDPR you have the right to access your personal data, to have inaccurate data corrected, to have data erased, to restrict or object to processing, to data portability, and to withdraw consent where processing is based on it.",
            "Under Art. 11 of the KVKK you have the right to learn whether your data is processed, to request information about it, to learn its purpose and whether it is used accordingly, to know the third parties it is transferred to, to request correction or deletion, to require that correction or deletion be notified to those third parties, to object to a result produced solely by automated analysis, and to claim compensation for damage caused by unlawful processing.",
          ],
        },
        {
          heading: "How to exercise them",
          body: [
            "Email us and we will respond within 30 days, as both the GDPR and the KVKK require. We may ask you to confirm your identity before acting on a request, but only where we genuinely cannot otherwise be sure who is asking.",
            "If you are unhappy with our response, you can complain to the Turkish Personal Data Protection Authority (Kişisel Verileri Koruma Kurumu, kvkk.gov.tr), or — if you are in the EEA — to the supervisory authority in your country of residence.",
          ],
        },
        {
          heading: "Security",
          body: [
            "The site is served over HTTPS. Enquiry submissions are validated and rate-limited on the server before being sent on. Access to our inbox is protected by multi-factor authentication. No system is perfectly secure, and we would rather say that plainly than imply otherwise.",
          ],
        },
        {
          heading: "Children",
          body: [
            "This site is aimed at businesses and is not directed at children. We do not knowingly collect personal data from anyone under 18.",
          ],
        },
        {
          heading: "Changes to this policy",
          body: [
            "If we change how we handle personal data, we will update this page and the date at the top of it. Material changes will be described here rather than quietly absorbed into the text.",
          ],
        },
      ],
    },

    {
      slug: "terms",
      title: "Terms of Service",
      summary:
        "The terms on which you use this website. Client work is governed by a separate signed agreement, not by this page.",
      sections: [
        {
          heading: "About these terms",
          body: [
            "These terms govern your use of this website. By using the site you accept them. If you do not accept them, please stop using the site.",
            "Client engagements are governed by a separate written agreement covering scope, fees, intellectual property, confidentiality and liability. Where that agreement and this page disagree, the signed agreement wins.",
          ],
          showCompanyDetails: true,
        },
        {
          heading: "Using this site",
          body: [
            "You may view, browse and print pages from this site for your own reference and to evaluate whether to work with us. That permission does not extend to republishing our content commercially, or presenting our work as your own.",
          ],
        },
        {
          heading: "Intellectual property",
          body: [
            "All content on this site — text, layout, typography, imagery, code and design — belongs to Aktays or is used with permission, and is protected by copyright and related rights.",
            "The Aktays name and wordmark are ours. Please do not use them to imply an association, endorsement or partnership that does not exist.",
          ],
        },
        {
          heading: "Client work shown here",
          body: [
            "Case studies are published with the relevant client's permission, or with identifying detail removed. Trade marks and brand names belonging to clients remain the property of those clients and appear here solely to describe work we did.",
            "Figures quoted in case studies describe results in a specific context, for a specific client. They are illustrative of what happened there and are not a promise of what will happen for you.",
          ],
        },
        {
          heading: "Acceptable use",
          body: ["You agree not to:"],
          bullets: [
            "use the site unlawfully, or in a way that infringes anyone's rights;",
            "attempt to gain unauthorised access to the site, its server or any connected system;",
            "submit false, abusive or deliberately misleading information through the enquiry form;",
            "use the form to send unsolicited commercial messages;",
            "scrape, mirror or systematically extract the site's content;",
            "knowingly introduce malware, or otherwise attempt to disrupt the site's availability.",
          ],
        },
        {
          heading: "Enquiries are not contracts",
          body: [
            "Submitting the enquiry form does not create a contract, and nothing on this site is an offer capable of acceptance. Prices and timelines shown here are indicative. Work begins only when both sides have signed a written agreement.",
          ],
        },
        {
          heading: "Links to other sites",
          body: [
            "Where we link elsewhere, we do so because we think it is useful. We do not control those sites and are not responsible for their content or their privacy practices.",
          ],
        },
        {
          heading: "Availability",
          body: [
            "We aim to keep the site available, but we do not guarantee it will be uninterrupted or error-free. We may change, suspend or withdraw any part of it without notice.",
          ],
        },
        {
          heading: "Limitation of liability",
          body: [
            "The site is provided as is. To the fullest extent permitted by law, we exclude liability for indirect or consequential loss, and for loss of profit, revenue, data or goodwill arising from your use of the site.",
            "Nothing in these terms limits or excludes liability for death or personal injury caused by negligence, for fraud, or for anything else that cannot lawfully be limited.",
          ],
        },
        {
          heading: "Governing law",
          body: [
            "These terms are governed by the laws of the Republic of Türkiye. The courts and enforcement offices of Istanbul (Çağlayan) have exclusive jurisdiction over any dispute arising from them.",
            "If you are a consumer resident in the EEA, this does not deprive you of the protection of the mandatory consumer law of your country of residence.",
          ],
        },
        {
          heading: "Changes",
          body: [
            "We may update these terms. The version published here is the one that applies, and the date at the top tells you when it last changed.",
          ],
        },
      ],
    },

    {
      slug: "cookies",
      title: "Cookie Policy",
      summary:
        "This site sets exactly one cookie, only when you choose a language. There is no analytics and no tracking.",
      sections: [
        {
          heading: "The short version",
          body: [
            "One cookie, set only if you actively switch language, remembering that choice so you are not sent back to the wrong language next time. No analytics, no advertising, no tracking, and no consent banner — because there is nothing here that requires consent.",
          ],
        },
        {
          heading: "What cookies are",
          body: [
            "A cookie is a small text file a website asks your browser to store. It can be read back later by the site that set it. Cookies are useful for remembering preferences; they are also the main mechanism behind tracking across the web. The difference is entirely in what a site chooses to do with them.",
          ],
        },
        {
          heading: "The cookie we set",
          bullets: [
            "Name: NEXT_LOCALE",
            "Purpose: remembers whether you chose English, Turkish or Arabic, so you land in the right language on your next visit.",
            "Set when: only when you click a language in the switcher. Simply visiting the site does not set it.",
            "Contains: a two-letter language code — en, tr or ar. Nothing else, and nothing that identifies you.",
            "Lifetime: 12 months.",
            "Type: strictly functional. Exempt from consent under the ePrivacy Directive and Turkish law, because it does only what you just asked it to do.",
          ],
        },
        {
          heading: "What we do not set",
          body: [
            "No Google Analytics or any other analytics. No advertising or remarketing pixels. No social media tracking. No session recording or heatmaps. No cross-site identifiers. We do not know how many people visited this page, and we have decided we can live with that.",
          ],
        },
        {
          heading: "Third-party requests that are not cookies",
          body: [
            "Two things worth naming, because they involve your browser talking to someone other than us even though no cookie is involved.",
          ],
          bullets: [
            "Google Fonts: our typefaces are loaded from Google's servers, so your browser requests them from Google, disclosing your IP address and user-agent. No cookie is set. A content blocker will stop this, and the site stays usable with fallback typefaces.",
            "Hosting logs: our host, Vercel, records standard server logs including IP addresses, for security and reliability. This is infrastructure logging, not a cookie, and you cannot opt out of it without not visiting the site.",
          ],
        },
        {
          heading: "Managing cookies",
          body: [
            "Every major browser lets you view, block and delete cookies in its settings. Because the only cookie we set is a language preference, blocking it costs you nothing except that the site will not remember your language between visits.",
          ],
        },
        {
          heading: "Changes",
          body: [
            "If we ever add a cookie, this page will say so before it appears — and if it is anything but strictly functional, we will ask for your consent first.",
          ],
        },
      ],
    },

    {
      slug: "accessibility",
      title: "Accessibility Statement",
      summary:
        "What we target, what we have actually done, and what we know is still imperfect.",
      sections: [
        {
          heading: "Our commitment",
          body: [
            "We design accessible products for our clients, so it would be difficult to justify not holding our own site to the same standard. This statement describes where it currently stands — including the parts that are not finished.",
          ],
        },
        {
          heading: "Conformance target",
          body: [
            "We target WCAG 2.2 Level AA. We believe the site substantially conforms, based on our own testing rather than a third-party audit. \"Substantially\" is doing real work in that sentence: it means we have tested thoroughly and have not commissioned an independent assessment.",
          ],
        },
        {
          heading: "What we have done",
          bullets: [
            "Semantic HTML with a single logical heading order on every page.",
            "All content reachable and operable by keyboard, with a visible focus indicator that is never removed.",
            "Text contrast meeting or exceeding AA against every background used on the site.",
            "Animation and smooth scrolling disabled entirely for visitors whose system requests reduced motion.",
            "Text that animates into view is present in the page from the start, so it is available to screen readers and search engines regardless of whether the animation runs.",
            "Full right-to-left support in Arabic, using logical CSS properties rather than a mirrored stylesheet.",
            "Form fields with real associated labels, errors announced to assistive technology, and no reliance on placeholder text as a label.",
            "Typography that scales with the viewport and respects browser zoom up to 200% without loss of content.",
          ],
        },
        {
          heading: "Known limitations",
          body: [
            "We would rather list these than claim they do not exist.",
          ],
          bullets: [
            "The case-study artwork is decorative and carries no text alternative, because it conveys no information. If we replace it with real photography, that will need revisiting.",
            "The custom cursor is decorative and appears only on fine-pointer devices; it is hidden under reduced-motion preferences, but it has not been tested against every assistive technology combination.",
            "We have not commissioned an independent accessibility audit. Our testing is thorough but it is our own.",
            "Typefaces load from a third-party service. If that request is blocked or slow, fallback fonts are used and line lengths shift slightly.",
          ],
        },
        {
          heading: "How we test",
          body: [
            "Keyboard-only navigation on every page, automated checks during development, colour contrast verified against the design tokens, and manual testing at 200% zoom and on small screens. Screen-reader testing is periodic rather than continuous.",
          ],
        },
        {
          heading: "Tell us if something is broken",
          body: [
            "If you hit a barrier on this site, please email us and describe what happened and what you were using. We treat accessibility reports as bugs, not as feature requests, and we will tell you when it is fixed.",
          ],
        },
      ],
    },
  ],
};
